---
title: "Data Mining for Decision Making"
author: "Instructor: Prof. Dr. Stephan Huber"
subtitle: "Presented by: Rasoul Kehaghi"
format: revealjs
editor: visual
fontsize: 20pt
---

# Question:

In this era, how often do you think data doubles in the world?

# Response:

Currently, the amount of accessible data doubles every two years (Open Science Conference, 2014).

# 1. Introduction

Today, information systems have large volume of data stored in these systems.

Also, decision makers need tools that can process the stored data for decision-making.

So we want to look at Data mining for decision making.

# 2. What Is Data Mining?

Data mining is the process of automatically discovering useful information in large data repositories.

# 3. Data Mining and Knowledge Discovery

Data mining is an integral part of knowledge discovery in databases (KDD), which is the overall process of converting raw data into useful information.

# 4. Steps of KDD

-   Input Data
-   Data Preprocessing
-   Data Mining
-   Postprocessing

# 5. Relationship with Other Fields

-   Statistics
-   Artificial intelligence (AI)
-   Machine learning (ML)

# 6. Data Mining Tasks

Data mining tasks are generally categorized into two main types:

-   Predictive Tasks: Predict the value of one attribute based on others
-   Descriptive Tasks: Identify patterns (e.g., correlations, trends, clusters, etc.) that summarize relationships in data

# 7. Importance of Data Mining for Decision Making

-   Businesses: Predict trends and improve marketing strategies.
-   Healthcare: Identify disease patterns for early intervention.
-   Education: Enhance student outcomes with predictive analysis and etc.

In general, data mining provides actionable insights. Also, reduces risks through data-driven decisions.

# 8. Example Use Cases

In business, we want to answer the following questions:

-   What products should be offered to potential customers?
-   When does a customer need a specific product?
-   What are the next likely purchases for this customer?
-   What is the relationship between a buyer's age and their purchasing behavior?

Therefore, The goal of data mining is to identify patterns in past data to clarify these needs and preferences, aiding future decisions.

# 9. Classroom practice

Before practicing what we learned, let's review some key points we talked about.

# What is Cluster Analysis?

Finding groups of objects where objects in a group are similar (or related) to one another and different from (or unrelated to) the objects in other groups.

One of the methods of clustering data is K-means.

# Classroom practice

Let's solve a clustering example together step by step:

-   Please load the following sample dataset:

``` markdown
data(iris)
```

-   Now we want to divide the data into 3 clusters based on two of the 4 features:

``` markdown
iris_data <- iris[, 1:2]
set.seed(123)
kmeans_result <- kmeans(iris_data, centers = 3)
```

-   Install ggplot2 package and visualize results:

``` markdown
print(kmeans_result)
install.packages("ggplot2")
library(ggplot2)
iris$Cluster <- as.factor(kmeans_result$cluster)
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Cluster)) +
geom_point(size = 3) +
labs(title = "K-Means Clustering on Iris Data", x = "Sepal Length", y = "Sepal Width")
```

# Result:

We just conducted a clustering method.

Welcome to the exciting world of data mining!

# 10. Conclusion

Data mining is indeed a powerful tool for decision making.

Data mining for decision making can empower organizations to act on patterns and trends, and make predictions based on them.

# 11. References

-   Open Science Conference. (2014). Digital data doubling every two years: A report on the rapid growth of information in the digital age. Open Science Conference Proceedings. Retrieved from https://www.open-science-conference.eu/wp-content/uploads/2017/03/03_Abstract.pdf
-   Tan, P., Steinbach, M., & Kumar, V. (2006). Introduction to data mining. Person.
-   Hahsler, M. (2024). An R companion for introduction to data mining. Figshare.https://doi.org/10.6084/m9.figshare.26750404